groups:
- name: blackboxes
  rules:
  - alert: ProbeDown
    # Condition for alerting
    expr: probe_success{job="blackbox"} == 0
    for: 2m
    # Annotation - additional informational labels to store more information
    annotations:
      title: 'Le site {{ $labels.instance }} est down'
      description: '{{ $labels.instance }} Est down depuis 2 Minutes (Job : {{ $labels.job }} ).'
    # Labels - additional labels to be attached to the alert
    labels:
      severity: 'high'
  - alert: ProbeDownLong
    # Condition for alerting
    expr: probe_success{job="blackbox"} == 0
    for: 1h
    # Annotation - additional informational labels to store more information
    annotations:
      title: 'Le site {{ $labels.instance }} est down'
      description: '{{ $labels.instance }} Est down depuis 60 minutes now (Job : {{ $labels.job }} ).'
    # Labels - additional labels to be attached to the alert
    labels:
      severity: 'critical'    
  - alert: InstanceDown
    # Condition for alerting
    expr: up{job="blackbox"} == 0
    for: 1m
    # Annotation - additional informational labels to store more information
    annotations:
      title: 'Instance {{ $labels.instance }} down'
      description: '{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute.'
    # Labels - additional labels to be attached to the alert
    labels:
      severity: 'critical'