providers:
  docker: 
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    directory: "/custom-conf/dynamic/"
    watch: true

global:
  checkNewVersion: true
  sendAnonymousUsage: true

#Global HTTP to HTTPS redirection
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: web-secure
          scheme: https
          permanent: true
  web-secure:
    address: ":443"
    
log:
  level: DEBUG
  #filePath: "/var/log/traefik.log"
accessLog:
  filePath: "/var/log/access.log"
  filters:    
    statusCodes:
      - "400-499"
api:
  dashboard: true

certificatesResolvers:
  lets-encrypt:
    acme:
      storage: /letsencrypt/acme.json
      tlsChallenge: {}
