http:         
  middlewares:
#
#  HTTPS Redirection
#
    force-https:
      redirectScheme:
        scheme: https
#
#  Authentication
#
    basic-auth:
      basicAuth:
        users:
          - "user:$2y$10$ZkKqodRFTqTper.DNIaen.k/nRG1VJ5XpQ724zfZKKMi1n0iGyKYG"
  #
  #     This is specific for joal, instead of configuring the web UI to connect to the joal deamon each time visiting the page, this add the configuration in the URL as GET requests. 
  #     "What about security?" would you ask, this is why there is a basic auth in the joal-chain 
  #        
    add-joal:
      redirectRegex:
        regex: "(.*)ratio.ayoute.ovh(.*)"
        replacement: "https://joal.ayoute.ovh/joal/ui?ui_credentials=%7B%0A%20%20%22host%22%3A%20%22joal.ayoute.ovh%22%2C%0A%20%20%22port%22%3A%20443%2C%0A%20%20%22pathPrefix%22%3A%20%22joal%22%2C%0A%20%20%22secretToken%22%3A%20%22Trololo%22%0A%7D"
    joal-chain:
      chain:
        middlewares:
          - add-joal@file
          - basic-auth@file
  #
  #  Add security policies to get a better score at SSLabs 
  #
    headers-control:
      headers:
        accessControlAllowMethods:
          - GET
          - OPTIONS
          - PUT
        addVaryHeader: true
        accessControlMaxAge: 100
        hostsProxyHeaders:
          - "X-Forwarded-Host"
        sslRedirect: true
        stsSeconds: 315360000
        stsIncludeSubdomains: true
        stsPreload: true
        forceSTSHeader: true
        frameDeny: true #overwritten by customFrameOptionsValue
        customFrameOptionsValue: "SAMEORIGIN" #CSP takes care of this but may be needed for organizr.
        contentTypeNosniff: true
        browserXssFilter: true
        # sslForceHost: true # add sslHost to all of the services
        # sslHost: "example.com"
        sslHost: "soflane.ovh"
        referrerPolicy: "same-origin"
        # Setting contentSecurityPolicy is more secure but it can break things. Proper auth will reduce the risk.
        # the below line also breaks some apps due to 'none' - sonarr, radarr, etc.
        #contentSecurityPolicy: "frame-ancestors '*.soflane.ovh:*';object-src 'none';script-src 'none';"
        featurePolicy: "camera 'none'; geolocation 'none'; microphone 'none'; payment 'none'; usb 'none';"
        customResponseHeaders:
          X-Robots-Tag: "none,noarchive,nosnippet,notranslate,noimageindex,"
          server: ""
          Permissions-Policy: "geolocation=(self 'https://*.soflane.ovh'), microphone=()"
          #Content-Security-Policy: "default-src 'self'"
    rate-limit:
      rateLimit: 
        average: 100
        burst: 50
    security-protocol:
      chain:
        middlewares:
          - force-https
          - rate-limit
          - headers-control
#
#  Specific redirections outside docker containers, another host in the same network for example
#
  routers:
    rt: 
      entryPoints: 
        - "web-secure"
      service: rt
      rule: Host(`router.example.com`)
      middlewares:
        - basic-auth@file
        - security-protocol@file
      tls:
          certResolver: lets-encrypt    
  services: 
    rt: 
      loadBalancer:
        servers:
          - url: "http://192.168.1.1/"


tls:
  options:
    default:
      minVersion: VersionTLS12
      sniStrict: true
      cipherSuites:  # Based on non weak ciphers on ssllabs.com on 02/11/2020 - https://www.smarthomebeginner.com/traefik-docker-security-best-practices/#Securing_Docker_Applications_using_Traefik
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
        - TLS_AES_128_GCM_SHA256
        - TLS_AES_256_GCM_SHA384
        - TLS_CHACHA20_POLY1305_SHA256
      curvePreferences:
        - CurveP521
        - CurveP384
          
