version: '3.5'
services: 
  deemix:
    image: registry.gitlab.com/bockiii/deemix-docker
    env_file: .env
    container_name: deemix
    hostname: ${DEEMIX_HOSTNAME}
    labels:
      - traefik.enable=true
      - traefik.http.routers.deemix.rule=Host(`${DEEMIX_HOSTNAME}.${MAIN_DOMAIN}`)
      - traefik.http.routers.deemix.tls.certresolver=lets-encrypt
      - traefik.http.routers.deemix.entrypoints=web-secure
      #Enable Auto-Updates (Watchtower)
      #- com.centurylinklabs.watchtower.enable=true
    volumes:
      - ${DEEMIX_DOWNLOADS}:/downloads
      - ${DEEMIX_CONFIG}:/config
    networks:
      - traefik
    expose:
      - 6595 
    restart: unless-stopped
  


networks:
  traefik:
    external: true
    name: traefik  
    
